Tests and upper-/lowercase support
10xjs/locale-emoji pull request #2
Opened 2017-02-28 19:54 UTC by Turbo87

This PR adds a few basic unit tests using mochajs.org and support for lowercase and uppercase LCIDs.

Resolves #1 

/cc @10xjs

2017-02-28 23:46 UTC, 10xjs requested changes
Changes look good!

A few nits on the tests.

2017-02-28 23:46 UTC, 10xjs commented on test.js
> +});
I'm not a huge fan of dynamic tests.

Make any `if` declaration static.  The `expect` inside a `foreach` is 👌 tho.

Also, trailing line break.

2017-02-28 23:49 UTC, 10xjs commented
@Turbo87 I'll get CI set up if you want to add a `.travis.yml` to this PR.

```yml
sudo: false
language: node_js
matrix:
  include:
    - node_js: 4
    - node_js: 5
    - node_js: 6
```

2017-03-01 08:18 UTC, Turbo87 commented
@10xjs thanks for the quick review. I've addressed your comments and added a TravisCI config file.

2017-03-01 20:19 UTC, 10xjs approved these changes

2017-03-01 20:19 UTC, merged